name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test distribution code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Run NPM install, build and test
        run: |
          npm install
          npm run build
          npm run test:ci

      - name: Publish artifact
        uses: actions/upload-artifact@v1
        with:
          name: laravel-passport-spa-js
          path: dist

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
