# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build distribution code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run NPM install
        run: npm install

      - name: Build the code
        run: npm run build

  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
